# Copyright New Relic, Inc.
# SPDX-License-Identifier: Apache-2.0
---

name: ".NET Pub Run tester"

concurrency:
  group: ${{ github.ref_name || github.ref || github.run_id }}-${{ github.workflow }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*_dotnet'

# Declare default permissions as read only.
permissions: read-all

jobs:
  publish-windows:
    uses: ./.github/workflows/publish-windows.yml
    secrets: inherit
    with:
      INITCONTAINER_LANGUAGE: dotnet-windows
      TARGETARCH: 2022