# Copyright New Relic, Inc.
# SPDX-License-Identifier: Apache-2.0
---
name: Windows Init Container Publish

on:
  workflow_call:
    inputs:
      INITCONTAINER_LANGUAGE:
        required: true
        type: string
      TARGETARCH:
        description: "Target Windows architecture for the build (e.g. 2022, 2025)"
        required: true
        type: string
      BUILD_ARGS:
        required: false
        type: string
        default: ""
      DOCKER_IMAGE_NAME:
        description: "Name for the published docker image, defaults to newrelic/newrelic-<INITCONTAINER_LANGUAGE>-init"
        required: false
        type: string
        default: ""
      DOCKER_IMAGE_TAG_SUFFIX:
        description: "Suffix to append to all version tags. (string with no preceding -)"
        required: false
        type: string
        default: ""
      DOCKER_IMAGE_TAG_IS_DEFAULT_SUFFIX:
        description: "Boolean indicating if both suffixed and non-suffixed tags should be produced. (true|false)"
        required: false
        type: boolean
        default: false

# Declare default permissions as read only.
permissions: read-all

jobs:
  publish:
    runs-on: windows-latest

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
        with:
          disable-sudo: true
          egress-policy: audit

      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # 4.2.2

      - name: Extract Agent Version Tags
        id: version
        uses: ./.github/actions/extract_agent_version_tags
        with:
          tag_suffix: ${{ inputs.DOCKER_IMAGE_TAG_SUFFIX }}
          is_default_suffix: ${{ inputs.DOCKER_IMAGE_TAG_IS_DEFAULT_SUFFIX }}

      - name: Generate Docker metadata (tags and labels)
        id: meta
        uses: docker/metadata-action@c1e51972afc2121e065aed6d45c65596fe445f3f # 5.8.0
        with:
          images: ${{ inputs.DOCKER_IMAGE_NAME || format('newrelic/newrelic-{0}{1}-init', inputs.INITCONTAINER_LANGUAGE, inputs.TARGETARCH) }}
          flavor: |
            latest=false
          tags: ${{ steps.version.outputs.tags }}

      - name: Login to Docker Hub Container Registry
        uses: docker/login-action@184bdaa0721073962dff0199f1fb9940f07167d1 # 3.5.0
        with:
          registry: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and publish init container image
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # 6.18.0
        with:
          push: true
          context: src/${{ inputs.INITCONTAINER_LANGUAGE }}/
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            AGENT_VERSION=${{ steps.version.outputs.agent_version }}
            TARGETARCH=${{ inputs.TARGETARCH }}
            ${{ inputs.BUILD_ARGS }}
